### ISSUE TITLE
Searching modules in the wrong path (epicapitest.py)

### ISSUE THREAD

**Issue by javiquinte** [EUDAT-B2SAFE/B2SAFE-core#47]
It seems that the file location is supposed to be one directory higher. For instance, epicclient.py is search in "../../cmd", but a "../" is missing. The same happens with the variable TEST_RESOURCES_PATH = '../tests/resources/', which actually misses also a "../"

**Comment by javiquinte** [comment]
The same seems to apply to epicclitest.py, epiccredtest.py, epicintgtest.py, testAuthzManager.py and testLogManager.py.

**Comment by NicolasLiampotis** [comment]
Closing this issue as invalid since both the current working dir and `../../cmd` are actually in the search path for modules:

    sys.path.append("../../cmd")

This is why both `import epicclient` and `TEST_RESOURCES_PATH = '../tests/resources/'` statements are working with no errors. 

Please, re-open if there's something I'm missing.
